export const theme = {
    button: {
        baseClassName: "button",
        color: {
            disabled: "bg-gray-500 hover:bg-gray-600",
            default: "bg-transparent",
            primary: "bg-blue-500 hover:bg-blue-600",
            secondary: "bg-gray-500 hover:bg-gray-600",
            success: "bg-green-500 hover:bg-green-600",
            warning: "bg-yellow-500 hover:bg-yellow-600",
            danger: "bg-red-500 hover:bg-red-600",
            info: "bg-teal-500 hover:bg-teal-600",
        },
        size: {
            xs: "py-1 px-2 text-xs",
            sm: "py-1 px-3 text-sm",
            md: "py-2 px-4 text-base",
            lg: "py-2 px-4 text-lg",
            xl: "py-3 px-5 text-xl",
            "2xl": "py-4 px-6 text-2xl",
        },
        rounded: {
            xs: "rounded",
            sm: "rounded-sm",
            md: "rounded-md",
            lg: "rounded-lg",
            xl: "rounded-xl",
            "2xl": "rounded-2xl",
            full: "rounded-full",
        },
        shadow: {
            xs: "shadow-xs",
            sm: "shadow-sm",
            md: "shadow",
            lg: "shadow-lg",
            xl: "shadow-xl",
            "2xl": "shadow-2xl",
        },
        role: "button",
    },
    card: {
        baseClassName: "card",
        color: {
            default: "bg-transparent",
            primary: "bg-blue-100",
            secondary: "bg-white",
            success: "bg-green-100",
            warning: "bg-yellow-100",
            danger: "bg-red-100",
            info: "bg-teal-100",
        },
        rounded: {
            xs: "rounded",
            sm: "rounded-sm",
            md: "rounded-md",
            lg: "rounded-lg",
            xl: "rounded-xl",
            "2xl": "rounded-2xl",
            full: "rounded-full",
        },
        shadow: {
            xs: "shadow-xs",
            sm: "shadow-sm",
            md: "shadow",
            lg: "shadow-lg",
            xl: "shadow-xl",
            "2xl": "shadow-2xl",
        },
    },
};

